// Liste des chansons Ky-Lin proposées au vote.
// slug: identifiant du fichier audio dans audio/<slug>.mp3 (et .wav si dispo)
// title: titre affiché (les noms alternatifs connus sont entre parenthèses)
const SONGS = [
  { slug: "a-thousand-and-three-stars", title: "A Thousand And Three Stars", wav: true },
  { slug: "dust-of-the-world", title: "Dust Of The World", wav: false },
  { slug: "over", title: "Over", wav: false },
  { slug: "poison", title: "Poison", wav: false },
  { slug: "surrender", title: "Surrender", wav: false },
  { slug: "too-bad", title: "Too Bad (Bad)", wav: false },
  { slug: "breath", title: "Breath", wav: false },
  { slug: "balboa", title: "Balboa (On My Way)", wav: true },
  { slug: "burden", title: "Burden", wav: false },
  { slug: "i-will-find", title: "I Will Find", wav: true },
  { slug: "in-the-eye", title: "In The Eye", wav: false },
  { slug: "cheerless-box", title: "Cheerless Box", wav: false },
  { slug: "twilight", title: "Twilight", wav: false },
  { slug: "snakes-house", title: "Snakes' House", wav: false },
  { slug: "these-boots", title: "These Boots Are Made For Walking", wav: false },
  { slug: "selfish", title: "Selfish", wav: true },
  { slug: "realm-of-fancy", title: "The Realm Of Fancy", wav: false },
  { slug: "lighthouse", title: "Lighthouse", wav: false },
  { slug: "used-branches-fall", title: "Used Branches Fall", wav: false },
  { slug: "eviction", title: "Eviction", wav: false },
  { slug: "breaking-the-glass", title: "Breaking The Glass", wav: false },
  { slug: "its-you", title: "It's You (Own Failure)", wav: false },
  { slug: "dance-with-me", title: "Dance With Me", wav: false },
  { slug: "welcome", title: "Welcome", wav: false },
  { slug: "too-late", title: "Too Late", wav: false },
  { slug: "sunset-love", title: "Sunset-Love", wav: false },
  { slug: "dont-pull-me-in", title: "Don't Pull Me In", wav: false },
  { slug: "say-my-name", title: "Say My Name", wav: false },
  { slug: "sun-that-turns-to-grey", title: "Sun That Turns To Grey", wav: false },
  { slug: "walking-on-your-shoulders", title: "Walking On Your Shoulders", wav: false },
  { slug: "everytime", title: "Everytime", wav: false },
  { slug: "into-the-night", title: "Into The Night (Goodie)", wav: false },
  { slug: "dead-and-gone", title: "Dead And Gone", wav: true },
  { slug: "let-it-die", title: "Let It Die (Ternaire)", wav: true },
  { slug: "upside-down", title: "Upside Down (Enemies)", wav: false },
  { slug: "hear-them-falling", title: "Hear Them Falling (Message)", wav: false },
  { slug: "the-ripper", title: "The Ripper (Trinaire / Triliaire)", wav: true },
  { slug: "modern-times", title: "Modern Times (Johnny Rules)", wav: false },
  { slug: "from-the-shell", title: "From The Shell", wav: false },
  { slug: "music", title: "Music", wav: false },
  { slug: "broken-past", title: "Broken Past", wav: false },
  { slug: "gerald-chanson", title: "Gerald Chanson", wav: false },
  { slug: "yesterday", title: "Yesterday", wav: false, noAudio: true },
];
