// Liste des chansons Ky-Lin proposées au vote.
// Tout est en mp3 (aucun wav — plus simple à héberger, pas de limite de taille GitHub).
// slug: identifiant du fichier audio dans audio/<slug>.mp3
// title: titre affiché (les noms alternatifs connus sont entre parenthèses)
// dualVersion: true => deux lecteurs distincts (nouvelle version = audio/<slug>.mp3,
// ancienne version = audio/<oldFile>)
const SONGS = [
  { slug: "a-thousand-and-three-stars", title: "A Thousand And Three Stars", dualVersion: true, oldFile: "a-thousand-and-three-stars-old.mp3" },
  { slug: "dust-of-the-world", title: "Dust Of The World", dualVersion: true, oldFile: "dust-of-the-world-old.mp3" },
  { slug: "over", title: "Over" },
  { slug: "poison", title: "Poison" },
  { slug: "surrender", title: "Surrender" },
  { slug: "too-bad", title: "Too Bad (Bad)", dualVersion: true, oldFile: "too-bad-old.mp3" },
  { slug: "breath", title: "Breath", dualVersion: true, oldFile: "breath-old.mp3" },
  { slug: "balboa", title: "Balboa (On My Way)", dualVersion: true, oldFile: "balboa-old.mp3" },
  { slug: "burden", title: "Burden" },
  { slug: "i-will-find", title: "I Will Find" },
  { slug: "i-will-find-2", title: "I Will Find (2)" },
  { slug: "in-the-eye", title: "In The Eye" },
  { slug: "cheerless-box", title: "Cheerless Box" },
  { slug: "twilight", title: "Twilight" },
  { slug: "snakes-house", title: "Snakes' House" },
  { slug: "these-boots", title: "These Boots Are Made For Walking" },
  { slug: "selfish", title: "Selfish" },
  { slug: "realm-of-fancy", title: "The Realm Of Fancy" },
  { slug: "lighthouse", title: "Lighthouse" },
  { slug: "used-branches-fall", title: "Used Branches Fall" },
  { slug: "eviction", title: "Eviction" },
  { slug: "breaking-the-glass", title: "Breaking The Glass" },
  { slug: "its-you", title: "It's You (Own Failure)", dualVersion: true, oldFile: "its-you-old.mp3" },
  { slug: "everytime", title: "Everytime" },
  { slug: "into-the-night", title: "Into The Night (Goodie)" },
  { slug: "let-it-die", title: "Let It Die (Ternaire)", dualVersion: true, oldFile: "let-it-die-old.mp3" },
  { slug: "upside-down", title: "Upside Down (Enemies)" },
  { slug: "hear-them-falling", title: "Hear Them Falling (Message)" },
  { slug: "the-ripper", title: "The Ripper (Trinaire / Triliaire)", dualVersion: true, oldFile: "the-ripper-old.mp3" },
  { slug: "modern-times", title: "Modern Times (Johnny Rules)", dualVersion: true, oldFile: "modern-times-johnnyrules.mp3" },
  { slug: "gerald-chanson", title: "Gerald Chanson" },
  { slug: "yesterday", title: "Yesterday" },
];
